### ISSUE TITLE
Compiler issues on various supported platforms

### ISSUE THREAD

**Issue by basisjp** [mintomic/mintomic#10]
First of all, thanks for a wonderful product.  I was able to drop it into my production code in about 5 minutes, and it worked out of the box on Win32/64, Linux, and MacOS - mostly.

Here are some compilation issues I ran into during the integration:

- Use of const for accessors
  - mint_load_xx_relaxed should take a "const mint_atomic32_t *object" vs a "mint_atomic32_t *object"
- Does not compile on Mac OS X 10.7 (Lion) (does work on Snow Leopard and Yosemite)
  - gcc version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.9.00)
  - ../../../include/mintomic/platform_detect.h:38:26: error: missing binary operator before token "("
  - #if defined(__has_feature)
       #if __has_feature(c_atomic)
          ...
- Compilation using 32-bit MSVC2010/2012 does not work
  - d:\xxx\include\mintomic\private/mintomic_msvc.h(141) : error C3861: '_InterlockedExchange64': identifier not found
  - Fails on XP, Vista, Win7
- Inclusion of Windows.h causes quite a bit of namespace pollution, even with WIN32_LEAN_AND_MEAN
  - Perhaps this could be leaned down to only the necessary include files

Thanks in advance for any consideration you could give to these issues.

J. P.

**Comment by preshing** [comment]
I submitted fixes for the first and third issues.
For the other two, I'm open to pull requests.

**Comment by basisjp** [comment]
Thanks for making those changes.  If I end up with a substantial improvement for the fourth issue (Windows namespace pollution), I'll submit a pull request.

**Comment by preshing** [comment]
Hi J.P., Mintomic is nearing the end of its life. I've basically moved all the atomic C code to Turf: https://github.com/preshing/turf/tree/master/turf/c

Further contributions welcome there!
